apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pod-dev
spec:
  project: default
  source:
    path: ./k8s-resources/nginx-pod/dev
    repoURL: https://github.com/nightmar39/tiger-mono-repo.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: nginx-pod-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
