apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-demo
  labels:
    app: blue-green-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: blue-green-demo
    name: in-cluster
  source:
    repoURL: https://github.com/nightmar39/cd-five-mins.git
    targetRevision: main
    path: ./k8s-resources/blue-green-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
